driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-8
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[test::default]
