---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      run_list:
        - recipe[apt]
  - name: ubuntu-14.04
    driver_config:
      run_list:
        - recipe[apt]
  - name: centos-7.2
    attributes:
      aptly:
        architectures: [amd64]

suites:
  - name: default
    run_list:
      - recipe[aptly::default]
      - recipe[aptly_test::default]
    attributes:
