---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  env: [CHEF_LICENSE=accept]

transport:
  name: dokken

provisioner:
  name: dokken
#  policyfile: test/Policyfile.rb # comment out if you use Policyfile
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
      pid_one_command: /bin/systemd
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
  - name: debian-8
    driver:
      image: dokken/debian-8
      pid_one_command: /sbin/init
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    run_list:
    - recipe[aptly_test::setup]
    - recipe[aptly::default]
    - recipe[aptly_test::default]
    attributes:
