---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-8
  - name: debian-9

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
