name              'aptly'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs/Configures aptly'
issues_url        'https://github.com/sous-chefs/aptly/issues'
source_url        'https://github.com/sous-chefs/aptly'
version           '2.3.3'
chef_version      '>= 16.0'

supports 'ubuntu'
supports 'debian'
